{{- if IsKubernetesVersionGe "1.16.0"}}
apiVersion: apps/v1
{{else}}
apiVersion: extensions/v1beta1
{{- end}}
kind: DaemonSet
metadata:
  name: azure-cni-networkmonitor
  namespace: kube-system
  labels:
    app: azure-cnms
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: azure-cnms
  template:
    metadata:
      labels:
        k8s-app: azure-cnms
{{- if not (IsKubernetesVersionGe "1.16.0")}}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
{{- end}}
{{- if IsKubernetesVersionGe "1.17.0"}}
      annotations:
        cluster-autoscaler.kubernetes.io/daemonset-pod: "true"
{{- end}}
    spec:
      priorityClassName: system-node-critical
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: "true"
        effect: NoSchedule
      - operator: "Exists"
        effect: NoExecute
      - operator: "Exists"
        effect: NoSchedule
      nodeSelector:
{{- if IsKubernetesVersionGe "1.19.0-alpha.2"}}
        kubernetes.io/os: linux
{{else}}
        beta.kubernetes.io/os: linux
{{- end}}
      containers:
        - name: azure-cnms
          image: {{ContainerImage "azure-cni-networkmonitor"}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: {{ContainerCPUReqs "azure-cni-networkmonitor"}}
              memory: {{ContainerMemReqs "azure-cni-networkmonitor"}}
            limits:
              cpu: {{ContainerCPULimits "azure-cni-networkmonitor"}}
              memory: {{ContainerMemLimits "azure-cni-networkmonitor"}}
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
          - name: ebtables-rule-repo
            mountPath: /var/run
          - name: log
            mountPath: /var/log
          - name: telemetry
            mountPath: /opt/cni/bin
      hostNetwork: true
      volumes:
      - name: log
        hostPath:
          path: /var/log
          type: Directory
      - name: ebtables-rule-repo
        hostPath:
          path: /var/run/
          type: Directory
      - name: telemetry
        hostPath:
          path: /opt/cni/bin
          type: Directory
