# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  ğŸ‘‹ Thanks for opening your first issue here! If you're reporting a ğŸ bug, please make sure you include steps to reproduce it.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  ğŸ’– Thanks for opening your first pull request! ğŸ’–
  We use [semantic commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) to streamline the release process. Before your pull request can be merged, you should **make sure your first commit and PR title** start with a semantic prefix.
  Examples of commit messages with semantic prefixes:
  - `fix: change azure disk cachingMode to ReadOnly`
  - `feat: make maximumLoadBalancerRuleCount configurable`
  - `docs: add note on AKS Engine and AKS relationship`

  Make sure to check out the [developer guide](https://github.com/Azure/aks-engine/blob/master/docs/community/developer-guide.md) for guidance on testing your change.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰
