log_level: debug

tide:
  # target_url: http://ci-bot-aks-ingress.eastus.cloudapp.azure.com/tide.html
  merge_method:
    Azure/aks-engine: squash
  queries:
  - repos:
    - Azure/aks-engine
    labels:
    - lgtm
    - approved
    missingLabels:
    - needs-ok-to-test
    - DO-NOT-MERGE
    - do-not-merge/work-in-progress
    - do-not-merge/hold
